### ISSUE TITLE
errors when running hc -vvv

### ISSUE THREAD

**Issue by Lydia823** [geodynamics/hc#2]
i installed he-1.0.7 according to README.TXT file.
but when i run 'hc -vvv', it turned out to errors like this:

[cc@dell hc-1.0.7]$ hc -vvv
hc: starting version compiled on Tue Aug  8 10:12:39 2017
prem_read_model: initialized PREM model from file prem/prem.dat
hc_assign_viscosity: read 4 layered viscosity[Pas] from visc.dat
hc_assign_viscosity: rough estimate of mean viscosity: 1.42802 x 1e+21 = 1.42802e+21 Pas
hc_init_main: using constant dln\rho/dln input density scaling of 0.2
hc_init: initializing for free-slip
hc_assign_density: error: can not open file dens.sh.dat for mode r access

**Comment by thwbecker** [comment]
Like it say, it cannot find the density input file. Please read the readme, and check hc -h

---
Thorsten W Becker - UTIG & DGS, JSG, UT Austin
